# roles/event_agent/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Create the 'openio' group
  group:
    name: openio
    gid: "{{ openio_group_openio_gid | default('220')}}"
  tags: install

- name: Create the 'openio' user
  user:
    name: openio
    comment: "openio account"
    uid: "{{ openio_user_openio_uid | default('120')}}"
    group: openio
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Test directories presence
  stat:
    path: "{{ item }}"
  register: _dir
  with_items:
    - "/etc/gridinit.d/{{ openio_event_agent_namespace }}"
    - "{{ openio_event_agent_sysconfig_dir }}/oio-event-agent-{{ openio_event_agent_serviceid }}"
    #- "{{ openio_event_agent_volume }}"
    - "/var/log/oio/sds/{{ openio_event_agent_namespace }}/oio-event-agent-{{ openio_event_agent_serviceid }}"

- name: Ensure directories exists
  file:
    path: "{{ item.item }}"
    state: directory
    owner: openio
    group: openio
    mode: 0755
    recurse: true
  with_items: "{{ _dir.results }}"
  when: not item.stat.exists
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "event_agent.conf.j2"
      dest: "{{ openio_event_agent_sysconfig_dir }}/\
        oio-event-agent-{{ openio_event_agent_serviceid }}/oio-event-agent-{{ openio_event_agent_serviceid }}.conf"
    - src: "event_agent_handlers.conf.j2"
      dest: "{{ openio_event_agent_sysconfig_dir }}/\
        oio-event-agent-{{ openio_event_agent_serviceid }}/oio-event-handlers.conf"
    - src: "gridinit_event_agent.conf.j2"
      dest: "{{ openio_event_agent_gridinit_dir }}/{{ openio_event_agent_gridinit_file_prefix }}\
        oio-event-agent-{{ openio_event_agent_serviceid }}.conf"
  register: _event_agent_conf

- name: restart event_agent
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{openio_event_agent_namespace}}-oio-event-agent-{{openio_event_agent_serviceid}}
  when:
    - _event_agent_conf.changed
    - not openio_event_agent_provision_only
  tags: configure
...
